name: mcedit2-docs

dependencies:
  - python=3.7
  - pyzmq
  - pyside
  - pyopengl
  - ipython
  - qtconsole
  - pygments
  - cython
  - numpy
  - pip:
    - pastebin
    - arrow
    - git+https://github.com/mcedit/pysideuic-pkg